root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main cmd/ordersystem/main.go cmd/ordersystem/wire_gen.go"
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html", "graphqls", "proto"]
  exclude_dir = [".docker", "tmp", "database", "docs", "api"]
  delay = 1000
  stop_on_error = false