version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
      - mysql_db_data:/var/lib/mysql
      - .docker/initdb:/docker-entrypoint-initdb.d

  migrate:
    image: migrate/migrate
    container_name: migrate-runner
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./database/migrations/:/migrations
    command: ["-path", "/migrations/", "-database", "mysql://${DB_USER}:${DB_PASSWORD}@tcp(mysql:3306)/orders", "up"]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
    mysql_db_data:
